name: ❓ Question
description: Ask a question about the template
title: "[QUESTION] "
labels: ["question", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're happy to help! Please check existing resources first.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any relevant context that might help us answer your question

  - type: textarea
    id: tried
    attributes:
      label: What Have You Tried?
      description: What research or attempts have you already made?

  - type: checkboxes
    id: resources
    attributes:
      label: Resources Checked
      description: Please confirm you've checked these resources
      options:
        - label: README.md
        - label: docs/ documentation
        - label: Existing issues
        - label: GitHub Discussions
